name: Mirror Repository

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🧁 Set up bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: 😺 Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: 🧁 add dependancies
      run: bun i

    - name: 🏗️ build
      run: bun run build
