name: Deployment

on: [ push ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Mirror push to target repository
      run: |
        git config --global user.name "louis-ermewa"
        git config --global user.email "louis.dauvergne.ext@ermewa.com"
        git remote add mirror https://github.com/ermewa/ui-wag12.git
        git branch -v
        git push https://louis-ermewa:${{ secrets.PAT }}@github.com/ermewa/ui-wag12.git HEAD:main --force
